theme: jekyll-theme-midnight

show_downloads: true  
google_analytics: UA-164529139-1

title:       QMRITools
name:        QMRITools
description: Processing tools related to quantitative MRI and spectroscopy of muscle, heart and nerves.
tagline:     QMRITools for Mathematica

url:         http://mfroeling.github.io/QMRITools
baseurl:     /QMRITools/

github:
  zip_url: https://github.com/mfroeling/QMRITools/releases/download/2.3.1/QMRITools.zip
  tar_url: https://github.com/mfroeling/QMRITools/releases/download/2.3.1/QMRITools.zip
  owner_url: https://github.com/mfroeling
  owner_name: Martijn Froeling, PhD